export const ServiceName = {
     getTransitStatusUrl: '/GetTrackingStatus?updateBased={0}&strCompany={1}',
     getTrackAndTraceUrl: '/GetTrackAndTraces?strCompany={0}',
     getUnlocUrl: '/GetUnloc?unLocCode={0}',
     getBookingsForWP: '/GetBookingsForWP?strCompany={0}',
     getBlDetail: '/GetBlDetail?TradeType={0}&BLID={1}&strCompany={2}',
     getStdCode: '/GetStdCodes?StdCodeType={0}&Subsidiary={1}',
     getInventories: '/GetInventories?Subsidiary={0}',
     getInventorysIsTotal: '/GetInventorysIsTotal?Subsidiary={0}',
     GetStdCodeForOrderDetail: 'GetAllDataForCombOboxOrderDetail?contactCode={0}&strCompany={1}',
     GetOrderDetail: 'GetOrderDetail?orderid={0}&Subsidiary={1}',
     SaveOrder: 'SaveOrder?Subsidiary={0}',
     UpdateOrder: 'UpdateOrder?Subsidiary={0}',
     GetOrdersForWP: 'GetOrdersForWP?strCompany={0}',
     DownloadFile: '/DownLoadFile?docNo={0}&strCompany={1}',
     Os_GetToday: '/OS_GetToday?subsidiary={0}&contactCode={1}&dcCode={2}',
     IE_GetToday: '/IE_GetToday?subsidiary={0}&contactCode={1}&dcCode={2}',
     GetBizAreas: '/GetBizAreas?strCompany={0}',
     DownloadFileStream: '/DownloadFileStream?docNo={0}&strCompany={1}',
     GetEquipmentCurrent: '/GetEquipmentCurrent?equipmentCode={0}&refDocNo={1}&refDocType={2}&subsiduaryId={3}',
     SaveEquipmentCurrent: '/SaveEquipmentCurrent?subsiduaryId={0}',
     GetEquipmentHistory: '/GetEquipmentHistory?equipmentCode={0}&refDocNo={1}&refDocType={2}&date={3}&subsiduaryId={4}',
     GetEquipments: '/GetEquipments?subsidiary={0}',
     getDebit: '/GetDebits?strCompany={0}',
     DeleteFile: '/DeleteDocument?docNo={0}&user={1}&Subsidiary={2}',
     GetTripRecords: '/GetTripRecords?Subsidiary={0}',
     ConfirmOrder: '/SaveOrderConfirm?Subsidiary={0}',
     GetKPIScoreView: '/GetKPIScoreView',
     GetKPIScoreViewDaily: '/GetKPIScoreViewDaily',
     GetKPIGroup: '/GetKPIGroup?subsiduaryId={0}&contactCode={1}',
     GetKPIYears: '/GetKPIYears',
     GetOnTimeOperationRawData: '/GetOnTimeOperationRawData',
     GetKPIDashboard: '/GetKPIDashboard?subsiduaryId={0}&contactCode={1}&year={2}&kpiGroup={3}',
     GetContactStdCodes: '/GetContactStdCodes?StdCodeType={0}&CodeVariant={1}&ContactCode={2}&Subsidiary={3}',
     GetLanguageResources: '/GetLanguageResources?language={0}',
     GetAllDataForCombOboxOrderDetail: '/GetAllDataForCombOboxOrderDetail?contactCode={0}&strCompany={1}',
     GetFreightInvoice: '/GetFreightInvoice?invoiceType={0}&docNo={1}&userId={2}&printOpt={3}&strCompany={4}',
     UpdateWPUser: '/UpdateWPUser',
     ResetPasswordWP: '/ResetPasswordWP?userid={0}&password={1}',
     GetUserLogin: '/GetUserLogin?UserID={0}',
     GetTransportOrderStatusForWp: 'GetTransportOrderStatusForWp?subsiduaryId={0}',
     GetTransportOrderDetailForWP: 'GetTransportOrderDetailForWP?Orderid={0}&OrderNo={1}&DeliveryMode={2}&strCompany={3}&contactCode={4}',
     GetCompanysbyType: '/GetCompanysbyType?strCompany={0}',
     GetUploadedDocuments: '/GetUploadedDocuments?RefNoValue={0}&DocRefType={1}&RefNoType={2}&strCompany={3}',
     GetEquipmentsByContact: '/GetEquipmentsByContact?subsidiary={0}&contactCode={1}',
     GetTransportOverview: '/TEGetTranstportOverView',
     GetHaulageOverview: '/TEGetHaulageOverview',
     GetWOCNTRManifests: '/GetWOCNTRManifests?woNo={0}&woItemNo={1}&subsidiaryId={2}',
     LoadDashboardConfig:'/LoadDashboardConfig?username={0}',
     SaveDashboardConfig:'/SaveDashboardConfig',
     GetTripDetail:'/GetTripDetail?tripNo={0}&dcNo={1}&subsidiaryId={2}'
};

export const OrderStatusServiceName = {
     getInboundOrdersStatus: '/GetInboundOrder?strCompany={0}',
     getOutboundOrdersStatus: '/GetOutboundOrder?strCompany={0}',
     GetInboundOrderDetail: 'GetInboundOrderDetail?orderid={0}&strCompany={1}',
     GetOutboundOrderDetail: '/GetOutboundOrderDetail?orderid={0}&strCompany={1}',
};
export const FeServicename = {
     GetFeCNTRHaulage: '/GetFECNTRHaulage?strCompany={0}'
};


