// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Microsoft.EntityFrameworkCore;
using Data.Logging.EFCore.Models;

namespace Data.Logging.EFCore.DB
{
    public partial class DBLOGSYSContext : DbContext
    {
        public DBLOGSYSContext()
        {
        }

        public DBLOGSYSContext(DbContextOptions<DBLOGSYSContext> options)
            : base(options)
        {
            AppContext.SetSwitch("Npgsql.EnableLegacyTimestampBehavior", true);
            AppContext.SetSwitch("Npgsql.DisableDateTimeInfinityConversions", true);
        }

        public virtual DbSet<UserActivityLogs> UserActivityLogs { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<UserActivityLogs>(entity =>
            {
                entity.ToTable("User_Activity_Logs", "LOGSYSTEM");

                entity.Property(e => e.Id).UseIdentityAlwaysColumn();

                entity.Property(e => e.FromServer).HasMaxLength(255);

                entity.Property(e => e.Ipaddress)
                    .HasMaxLength(20)
                    .HasColumnName("IPAddress");

                entity.Property(e => e.MetaData).HasColumnType("json");

                entity.Property(e => e.Remarks).HasMaxLength(4000);

                entity.Property(e => e.SystemId).HasMaxLength(50);

                entity.Property(e => e.UserId).HasMaxLength(50);
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}