// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable

namespace Data.Logging.EFCore.Models
{
    public partial class UserActivityLogs
    {
        public int Id { get; set; }
        public string UserId { get; set; }
        public DateTime? CreateDate { get; set; }
        public string Ipaddress { get; set; }
        public string SystemId { get; set; }
        public string FromServer { get; set; }
        public string MetaData { get; set; }
        public string Remarks { get; set; }
    }
}