apiVersion: apps/v1
kind: Deployment
metadata:
  name: authentication
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: authentication
  template:
    metadata:
      labels:
        app: authentication
    spec:
      containers:
      - image: cuongtran630/apiauthentication
        name: authentication
        ports:
        - containerPort: 80
