apiVersion: apps/v1
kind: Deployment
metadata:
  name: authentication
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: authentication
  template:
    metadata:
      labels:
        app: authentication
    spec:
      containers:
      - image: bomtan2000/authentication
        name: authentication
        ports:
        - containerPort: 5006
