apiVersion: apps/v1
kind: Deployment
metadata:
  name: booking
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: booking
  template:
    metadata:
      labels:
        app: booking
    spec:
      containers:
      - image: bomtan2000/booking
        name: booking
        ports:
        - containerPort: 5008
