apiVersion: apps/v1
kind: Deployment
metadata:
  name: fileupload
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: fileupload
  template:
    metadata:
      labels:
        app: fileupload
    spec:
      containers:
      - image: bomtan2000/fileupload
        name: fileupload
        ports:
        - containerPort: 80
