apiVersion: apps/v1
kind: Deployment
metadata:
  name: fmbp
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: fmbp
  template:
    metadata:
      labels:
        app: fmbp
    spec:
      containers:
      - image: cuongtran630/webui
        name: fmbp
        ports:
        - containerPort: 80
