apiVersion: apps/v1
kind: Deployment
metadata:
  name: logging
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: logging
  template:
    metadata:
      labels:
        app: logging
    spec:
      containers:
      - image: cuongtran630/logging
        name: logging
        ports:
        - containerPort: 5003
