// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Data.Administrator.EFCore.Models
{
    public partial class AnnouncementAck
    {
        public int Id { get; set; }
        public int AnnouncementId { get; set; }
        public DateTime? AckcreateDate { get; set; }
        public int AckcreatedBy { get; set; }
        public string AckSignature { get; set; }
    }
}