// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Service.Core;

namespace Data.Administrator.EFCore.Models
{
    public partial class Announcement : BaseEntity
    {
        public DateTime? ExpiredDate { get; set; }
        public string AnnounceType { get; set; }
        public string Subject { get; set; }
        public string AnnounceText { get; set; }
        public string AnnounceTypeDesc { get; set; }
        public char? IsRequireEndorse { get; set; }
        public string Attach1 { get; set; }
        public string Attach2 { get; set; }
        public string Attach3 { get; set; }
        public string Attach4 { get; set; }
        public string UserGroup { get; set; }
        public string UserGroupDesc { get; set; }
        public int? ReadCount { get; set; }
        public int CompanyId { get; set; }
    }
}