// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Data.Administrator.EFCore.Models
{
    public partial class AnnouncementView
    {
        public int Id { get; set; }
        public DateTime? ViewTimeStamp { get; set; }
        public int ViewUserId { get; set; }
        public int AnnouncementId { get; set; }
    }
}