// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Service.Core;

namespace Data.Administrator.EFCore.Models
{
    public partial class Clients : BaseEntity
    {
        /// <summary>
        /// Customer Name / Person Name\n
        /// </summary>
        public string ClientName { get; set; }
        public string Address { get; set; }
        public string PostalCode { get; set; }
        public string ContactPerson { get; set; }
        public string MobileNo { get; set; }
        public int CompanyId { get; set; }
        /// <summary>
        /// 1: VALID\n0 / NULL : INVALID
        /// </summary>
        public string Remark { get; set; }
        public string Country { get; set; }
        public string CustomField01 { get; set; }
        public string CustomField02 { get; set; }
        public string CustomField03 { get; set; }
        public string CustomField04 { get; set; }
        public string CustomField05 { get; set; }
        public string CreateByName { get; set; }
        public string UpdatedByName { get; set; }
    }
}