// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable

namespace Data.Administrator.EFCore.Models
{
    public partial class Country
    {
        public string CountryCode { get; set; }
        public string CountryCode3 { get; set; }
        public string CountryDesc { get; set; }
        public string CountryCodeNum { get; set; }
        public string Remark { get; set; }
    }
}