// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Data.Administrator.EFCore.Models
{
    public partial class DriverCheckInOut
    {
        public int Id { get; set; }
        public int CompanyId { get; set; }
        public int DriversId { get; set; }
        public string EquipmentNo { get; set; }
        public DateTime? CreateDate { get; set; }
        public string CreatedLocation { get; set; }
        public string PlaceDesc { get; set; }
        public int? Mileage { get; set; }
        public DateTime? CheckOutTime { get; set; }
        public string CheckOutLocation { get; set; }
        public string CheckOutPlaceDesc { get; set; }
        public int? PeriodMin { get; set; }
    }
}