// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Service.Core;

namespace Data.Administrator.EFCore.Models
{
    public partial class Places : BaseEntity
    {
        public string PlaceDesc { get; set; }
        public string Address { get; set; }
        public string Postalcode { get; set; }
        public string ContactPerson { get; set; }
        public string MobileNo { get; set; }
        public int CompanyId { get; set; }
        /// <summary>
        /// Related with Customer Id \nIt could be Null , Null means Not related with Customer \n
        /// </summary>
        public int? ClientsId { get; set; }
        public string Remark { get; set; }
        public string Country { get; set; }
        public string CustomField01 { get; set; }
        public string CustomField02 { get; set; }
        public string CustomField03 { get; set; }
        public string CustomField04 { get; set; }
        public string CustomField05 { get; set; }
        public string CreatedByName { get; set; }
        public string UpdatedByName { get; set; }
    }
}