// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Service.Core;
using System;
using System.Collections.Generic;

namespace Data.Authentication.EFCore.Models
{
    public partial class Company : BaseEntity
    {
        public string CompanyName { get; set; }
        public string Addr { get; set; }
        public string PostalCode { get; set; }
        public string ContactPerson { get; set; }
        public string ContactEmail { get; set; }
        public string CompanyStatus { get; set; }
        public string Currency { get; set; }
        public string ShortCode { get; set; }
        public string Country { get; set; }
        public string Remark { get; set; }
    }
}