// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Data.Authentication.EFCore.Models
{
    public partial class Country
    {
        public int Id { get; set; }
        public string CountryCode { get; set; }
        public string CountryCode3 { get; set; }
        public string CountryName { get; set; }
    }
}