// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Data.Authentication.EFCore.Models
{
    public partial class GlobalConfiguration
    {
        public int Id { get; set; }
        public string NameSetting { get; set; }
        public string ValueSetting { get; set; }
        public string Module { get; set; }
        public string TypeValue { get; set; }
        public string Description { get; set; }
    }
}