// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Data.Authentication.EFCore.Models
{
    public partial class GroupPermission
    {
        public int GroupId { get; set; }
        public string SystemCode { get; set; }
        public string PageCode { get; set; }
        public char New { get; set; }
        public char Search { get; set; }
        public char Store { get; set; }
        public char Export { get; set; }
        public char Preview { get; set; }
        public char Del { get; set; }
        public char Plan { get; set; }
        public char Run { get; set; }

        public virtual Groups Group { get; set; }
    }
}