// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Service.Core;
using System;
using System.Collections.Generic;

namespace Data.Authentication.EFCore.Models
{
    public partial class Groups : BaseEntity
    {
        public Groups()
        {
            GroupPermission = new HashSet<GroupPermission>();
            User2Group = new HashSet<User2Group>();
        }

        public string GroupName { get; set; }
        public string Notes { get; set; }

        public virtual ICollection<GroupPermission> GroupPermission { get; set; }
        public virtual ICollection<User2Group> User2Group { get; set; }
    }
}