// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Data.Authentication.EFCore.Models
{
    public partial class Menu
    {
        public string MenuCode { get; set; }
        public string MenuName { get; set; }
        public string SystemCode { get; set; }
        public string PageCode { get; set; }
        public char? IsGroup { get; set; }
        public string ParentMenu { get; set; }
        public string Icon { get; set; }
    }
}