// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Data.Authentication.EFCore.Models
{
    public partial class Platform
    {
        public Platform()
        {
            Systems = new HashSet<Systems>();
        }

        public string PlatformCode { get; set; }
        public string PlatformDesc { get; set; }
        public char IsValid { get; set; }

        public virtual ICollection<Systems> Systems { get; set; }
    }
}