// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Data.Authentication.EFCore.Models
{
    public partial class RefreshToken
    {
        public int Id { get; set; }
        public string RefreshTokenId { get; set; }
        public int UserId { get; set; }
        public DateTime IssuedDate { get; set; }
        public DateTime ExpiresDate { get; set; }
        public string ProtectedTicket { get; set; }
        public string AccessToken { get; set; }
    }
}