// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Data.Authentication.EFCore.Models
{
    public partial class StdCodes
    {
        public string CodeGroup { get; set; }
        public string Code { get; set; }
        public string CodeDesc { get; set; }
        public char? IsValid { get; set; }
        public int? SeqNo { get; set; }
        public string CodeVariant { get; set; }
    }
}