// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Data.Authentication.EFCore.Models
{
    public partial class Systems
    {
        public string SystemCode { get; set; }
        public string SystemDesc { get; set; }
        public char IsValid { get; set; }
        public string PlatformCode { get; set; }

        public virtual Platform PlatformCodeNavigation { get; set; }
    }
}