// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Data.Authentication.EFCore.Models
{
    public partial class User2Company
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public int CompanyId { get; set; }
    }
}