// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Service.Core;
using System;
using System.Collections.Generic;

namespace Data.Authentication.EFCore.Models
{
    public partial class Users : BaseEntity
    {
        public Users()
        {
            User2Group = new HashSet<User2Group>();
        }

        public string DisplayName { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string LoginId { get; set; }
        public string Email { get; set; }
        public string MobileNo { get; set; }
        public string RegType { get; set; }
        public string Pwd { get; set; }
        public short? FailedCountLogin { get; set; }
        public string VerifyGuiId { get; set; }

        public virtual UserDetail UserDetail { get; set; }
        public virtual ICollection<User2Group> User2Group { get; set; }
    }
}